services:
  laravel:
    image: laravel
    container_name: laravel
    working_dir: /var/www
    volumes:
      - laraveldata:/var/www    # Full Laravel project inside named volume
    networks:
      - appnet
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    user: root
    volumes:
      - laraveldata:/var/www:cached  # Mount same volume for Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - appnet
    depends_on:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - appnet

volumes:
  laraveldata:
  dbdata:

networks:
  appnet:
